name: Generate Snake Animation

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: vippium
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
          palette: "['#FFA500', '#FFD580', '#FF8C00', '#FFA07A']"  # Orange theme
          background: transparent

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
